#!/usr/bin/env node
/**
 * Downloads a self-contained PHP CLI runtime into resources/php so the
 * desktop app bundles its own PHP with no system dependency.
 *
 * Windows: official php.net non-thread-safe (nts) x64 zip. The zip ships the
 * extension DLLs under ext/ but no php.ini, so this script writes one next
 * to php.exe that enables everything Microweber 2.0.20 needs (intl, sodium,
 * gd, zip, ...). php-server.js and first-run.js pass it with -c.
 * Linux/macOS: pass --url pointing at a prebuilt static PHP
 * (e.g. from static-php-cli, see .github/workflows/desktop.yml) or set
 * FLAREWEBER_PHP_URL. Static builds compile the extensions in.
 *
 * Usage: node scripts/fetch-runtime.mjs [--url <zip|tar.gz>] [--dir resources/php]
 */

import {
  mkdirSync,
  existsSync,
  createWriteStream,
  chmodSync,
  rmSync,
  renameSync,
  statSync,
  readdirSync,
  writeFileSync,
} from 'node:fs';
import { createGunzip } from 'node:zlib';
import { pipeline } from 'node:stream/promises';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

const WINDOWS_LATEST =
  'https://windows.php.net/downloads/releases/latest/php-8.3-nts-Win32-vs16-x64-latest.zip';

// Extensions enabled in the generated php.ini. php.net zips include every one
// of these as ext/php_<name>.dll (sodium ships as php_sodium.dll).
const WINDOWS_EXTENSIONS = [
  'curl', 'openssl', 'mbstring', 'pdo_sqlite', 'sqlite3', 'fileinfo',
  'gd', 'intl', 'zip', 'sodium', 'exif', 'bcmath',
];

// Extensions the runtime must be able to load, whatever the platform.
const REQUIRED_EXTENSIONS = ['intl', 'sodium', 'pdo_sqlite', 'gd', 'zip', 'mbstring', 'curl', 'openssl'];

function arg(name, fallback) {
  const i = process.argv.indexOf(`--${name}`);
  return i !== -1 && process.argv[i + 1] ? process.argv[i + 1] : fallback;
}

async function download(url, dest) {
  const res = await fetch(url, { redirect: 'follow' });
  if (!res.ok || !res.body) throw new Error(`download failed: ${res.status} ${url}`);
  await pipeline(res.body, createWriteStream(dest));
}

function findFile(dir, name, minSize = 0) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      const found = findFile(full, name, minSize);
      if (found) return found;
    } else if (entry.name === name && statSync(full).size > minSize) {
      return full;
    }
  }
  return null;
}

/**
 * Write php.ini next to php.exe. extension_dir stays relative ("ext"): PHP on
 * Windows resolves extension DLLs through LoadLibrary, which searches the
 * php.exe directory first, so the runtime works wherever the app is installed.
 */
function writeWindowsIni(outDir) {
  const iniPath = path.join(outDir, 'php.ini');
  const missing = WINDOWS_EXTENSIONS.filter(
    (ext) => !existsSync(path.join(outDir, 'ext', `php_${ext}.dll`))
  );
  if (missing.length) {
    throw new Error(`php.net zip is missing extension DLLs: ${missing.join(', ')}`);
  }

  const lines = [
    '; Generated by scripts/fetch-runtime.mjs for the bundled Windows runtime.',
    '; php-server.js passes this file with -c so the built-in server and',
    '; artisan share it. Regenerate by deleting resources/php.',
    '[PHP]',
    'extension_dir = "ext"',
    ...WINDOWS_EXTENSIONS.map((ext) => `extension=${ext}`),
    'memory_limit = 1024M',
    'max_execution_time = 0',
    'upload_max_filesize = 64M',
    'post_max_size = 64M',
    'display_errors = Off',
    'log_errors = On',
    'error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT',
    'date.timezone = UTC',
    '',
  ];
  writeFileSync(iniPath, lines.join('\r\n'));
  console.log(`Wrote ${iniPath}`);
  return iniPath;
}

function verify(phpPath, iniPath) {
  const args = iniPath ? ['-c', iniPath] : [];
  const check = REQUIRED_EXTENSIONS.map((e) => `'${e}'`).join(',');
  const out = execFileSync(
    phpPath,
    [
      ...args,
      '-r',
      `$m=array_filter([${check}],fn($e)=>!extension_loaded($e));` +
        `echo PHP_VERSION,"\\n";if($m){fwrite(STDERR,'missing: '.implode(',',$m)."\\n");exit(1);}`,
    ],
    { encoding: 'utf8' }
  ).trim();
  console.log(`Bundled PHP ${out} at ${phpPath} (intl, sodium, pdo_sqlite, gd, zip ok)`);
}

async function main() {
  const outDir = path.resolve(ROOT, arg('dir', 'resources/php'));
  const binary = process.platform === 'win32' ? 'php.exe' : 'php';
  const phpPath = path.join(outDir, binary);
  const isWindows = process.platform === 'win32';

  if (existsSync(phpPath)) {
    console.log(`PHP runtime already present in ${outDir}`);
    const iniPath = isWindows && !existsSync(path.join(outDir, 'php.ini')) ? writeWindowsIni(outDir) : null;
    verify(phpPath, iniPath || (isWindows ? path.join(outDir, 'php.ini') : null));
    return;
  }

  const url = arg('url', process.env.FLAREWEBER_PHP_URL || (isWindows ? WINDOWS_LATEST : null));
  if (!url) {
    console.error(
      'No PHP runtime URL for this platform. Provide --url or FLAREWEBER_PHP_URL ' +
        'pointing to a self-contained PHP tarball (see .github/workflows/desktop.yml ' +
        'for the static-php-cli build used in CI).'
    );
    process.exit(1);
  }

  mkdirSync(outDir, { recursive: true });
  const tmp = path.join(outDir, path.basename(new URL(url).pathname) || 'php-runtime');

  console.log(`Downloading PHP runtime from ${url}...`);
  await download(url, tmp);

  if (tmp.endsWith('.zip')) {
    execFileSync('tar', ['-xf', tmp, '-C', outDir], { stdio: 'inherit' });
    rmSync(tmp);
    if (!existsSync(phpPath)) {
      const found = findFile(outDir, binary, 1_000_000);
      if (!found) throw new Error('php binary not found inside archive');
      renameSync(found, phpPath);
    }
  } else if (tmp.endsWith('.gz')) {
    const { createReadStream } = await import('node:fs');
    await pipeline(createReadStream(tmp), createGunzip(), createWriteStream(phpPath));
    rmSync(tmp);
  } else {
    renameSync(tmp, phpPath);
  }

  if (!isWindows) chmodSync(phpPath, 0o755);

  const iniPath = isWindows ? writeWindowsIni(outDir) : null;
  verify(phpPath, iniPath);
}

main().catch((err) => {
  console.error(err.message);
  process.exit(1);
});
