<?php

namespace FlareWeber\Compiler;

/**
 * Turns compiled site data into D1 seed SQL that matches worker/schema.sql.
 */
class SeedGenerator
{
    /**
     * @param array<int, array<string, mixed>> $products
     */
    public function generate(array $products, array $settings = []): string
    {
        $sql = "-- Generated by FlareWeber Site Compiler at " . now()->toIso8601String() . "\n";
        $sql .= "DELETE FROM cart_items; DELETE FROM carts; DELETE FROM order_items;\n";
        $sql .= "DELETE FROM inventory; DELETE FROM product_variants; DELETE FROM products;\n\n";

        foreach ($products as $product) {
            $sql .= $this->productInsert($product);
        }

        foreach ($settings as $key => $value) {
            $sql .= sprintf(
                "INSERT OR REPLACE INTO settings (key, value) VALUES (%s, %s);\n",
                $this->quote((string) $key),
                $this->quote((string) $value)
            );
        }

        return $sql;
    }

    /**
     * @param array<string, mixed> $product
     */
    private function productInsert(array $product): string
    {
        $id = (int) $product['id'];

        $sql = sprintf(
            "INSERT INTO products (id, slug, title, description, image, published) VALUES (%d, %s, %s, %s, %s, 1);\n",
            $id,
            $this->quote($product['slug']),
            $this->quote($product['title']),
            $this->quote($product['description'] ?? ''),
            $this->quote($product['image'] ?? '')
        );

        $sql .= sprintf(
            "INSERT INTO product_variants (id, product_id, sku, title, price_cents, currency) VALUES (%d, %d, %s, %s, %d, %s);\n",
            $this->variantId($id),
            $id,
            $this->quote('MW-' . $id),
            $this->quote('Default'),
            (int) ($product['price_cents'] ?? 0),
            $this->quote($product['currency'] ?? 'USD')
        );

        $sql .= sprintf(
            "INSERT INTO inventory (variant_id, quantity) VALUES (%d, %d);\n",
            $this->variantId($id),
            (int) ($product['quantity'] ?? 0)
        );

        return $sql;
    }

    private function variantId(int $productId): int
    {
        return $productId * 10;
    }

    private function quote(?string $value): string
    {
        if ($value === null) {
            return "''";
        }

        return "'" . str_replace("'", "''", $value) . "'";
    }
}
