<?php

namespace FlareWeber\Compiler;

/**
 * Turns extracted products (contract E) into D1 seed SQL for worker/schema.sql.
 *
 * Only upserts are emitted (INSERT ... ON CONFLICT DO UPDATE). Products that
 * disappeared from the CMS are deactivated (products.is_active = 0), never
 * deleted, so orders and carts keep their references. Nothing here ever
 * touches orders, order_items, carts, cart_items, customers or form_entries.
 */
class SeedGenerator
{
    public const UNLIMITED = -1;

    /**
     * @param array<int, array<string, mixed>> $products
     * @param array<string, scalar|null> $settings   key/value rows for the settings table
     * @param bool $syncInventory   when false, existing inventory quantities are left alone
     */
    public function generate(array $products, array $settings = [], bool $syncInventory = true): string
    {
        // product_categories.active comes from worker/migrations/0004; dropped
        // mappings are flagged inactive instead of deleted.
        $sql = '-- Generated by FlareWeber Site Compiler at ' . gmdate('c') . "\n\n";

        $sql .= $this->categoryUpserts($products);

        $ids = [];
        foreach ($products as $product) {
            $id = (int) ($product['id'] ?? 0);
            if ($id <= 0) {
                continue;
            }

            $ids[] = $id;
            $sql .= $this->productUpsert($product, $id, $syncInventory);
        }

        $sql .= $this->deactivateMissing($ids);

        foreach ($settings as $key => $value) {
            $sql .= sprintf(
                "INSERT INTO settings (key, value) VALUES (%s, %s) ON CONFLICT(key) DO UPDATE SET value = excluded.value;\n",
                $this->quote((string) $key),
                $this->quote($value === null ? '' : (string) $value)
            );
        }

        return $sql;
    }

    /** @param array<int, array<string, mixed>> $products */
    private function categoryUpserts(array $products): string
    {
        $categories = [];

        foreach ($products as $product) {
            foreach ($product['categories'] ?? [] as $category) {
                $id = (int) ($category['id'] ?? 0);
                if ($id > 0) {
                    $categories[$id] = $category;
                }
            }
        }

        if ($categories === []) {
            return '';
        }

        ksort($categories);
        $sql = '';

        foreach ($categories as $id => $category) {
            $name = (string) ($category['name'] ?? ('Category ' . $id));
            $slug = (string) ($category['slug'] ?? '');
            if ($slug === '') {
                $slug = 'category-' . $id;
            }

            $parent = isset($category['parent_id']) && (int) $category['parent_id'] > 0
                ? (string) (int) $category['parent_id']
                : 'NULL';

            $sql .= sprintf(
                "INSERT INTO categories (id, slug, name, parent_id) VALUES (%d, %s, %s, %s) "
                . "ON CONFLICT(id) DO UPDATE SET slug = excluded.slug, name = excluded.name, parent_id = excluded.parent_id;\n",
                $id,
                $this->quote($slug),
                $this->quote($name),
                $parent
            );
        }

        return $sql . "\n";
    }

    /** @param array<string, mixed> $product */
    private function productUpsert(array $product, int $id, bool $syncInventory): string
    {
        $active = array_key_exists('is_active', $product) ? (bool) $product['is_active'] : true;

        $variants = $this->variantsFor($product, $id);
        $images = array_values(array_filter(array_map('strval', (array) ($product['images'] ?? []))));

        $sql = sprintf(
            "INSERT INTO products (id, slug, title, description, image, is_active, price_cents, currency, sku, images_json) "
            . "VALUES (%d, %s, %s, %s, %s, %d, %d, %s, %s, %s) "
            . "ON CONFLICT(id) DO UPDATE SET slug = excluded.slug, title = excluded.title, "
            . "description = excluded.description, image = excluded.image, is_active = excluded.is_active, "
            . "price_cents = excluded.price_cents, currency = excluded.currency, sku = excluded.sku, images_json = excluded.images_json;\n",
            $id,
            $this->quote((string) ($product['slug'] ?? ('product-' . $id))),
            $this->quote((string) ($product['title'] ?? '')),
            $this->quote((string) ($product['description'] ?? '')),
            $this->nullableQuote($product['image'] ?? null),
            $active ? 1 : 0,
            (int) ($product['price_cents'] ?? $variants[0]['price_cents']),
            $this->quote($variants[0]['currency']),
            $this->nullableQuote($product['sku'] ?? null),
            $this->quote((string) json_encode($images, JSON_UNESCAPED_SLASHES))
        );

        foreach ($variants as $variant) {
            $sql .= sprintf(
                "INSERT INTO product_variants (id, product_id, sku, title, price_cents, currency) VALUES (%d, %d, %s, %s, %d, %s) "
                . "ON CONFLICT(id) DO UPDATE SET product_id = excluded.product_id, sku = excluded.sku, "
                . "title = excluded.title, price_cents = excluded.price_cents, currency = excluded.currency;\n",
                $variant['id'],
                $id,
                $this->nullableQuote($variant['sku']),
                $this->quote($variant['title']),
                $variant['price_cents'],
                $this->quote($variant['currency'])
            );

            $sql .= sprintf(
                "INSERT INTO inventory (variant_id, quantity) VALUES (%d, %d) ON CONFLICT(variant_id) DO %s;\n",
                $variant['id'],
                $variant['quantity'],
                $syncInventory ? 'UPDATE SET quantity = excluded.quantity' : 'NOTHING'
            );
        }

        $categoryIds = [];
        foreach ($product['categories'] ?? [] as $category) {
            $categoryId = (int) ($category['id'] ?? 0);
            if ($categoryId > 0) {
                $categoryIds[] = $categoryId;
                $sql .= sprintf(
                    "INSERT INTO product_categories (product_id, category_id, active) VALUES (%d, %d, 1) "
                    . "ON CONFLICT(product_id, category_id) DO UPDATE SET active = 1;\n",
                    $id,
                    $categoryId
                );
            }
        }

        // Mappings dropped in the CMS are flagged inactive rather than deleted.
        $sql .= sprintf(
            "UPDATE product_categories SET active = 0 WHERE product_id = %d%s;\n",
            $id,
            $categoryIds !== [] ? ' AND category_id NOT IN (' . implode(', ', $categoryIds) . ')' : ''
        );

        return $sql . "\n";
    }

    /**
     * Explicit variants, or the default variant (id = product id * 10) the
     * store shim relies on.
     *
     * @param array<string, mixed> $product
     * @return array<int, array{id: int, sku: string|null, title: string, price_cents: int, currency: string, quantity: int}>
     */
    private function variantsFor(array $product, int $productId): array
    {
        $currency = strtoupper((string) ($product['currency'] ?? 'USD')) ?: 'USD';
        $variants = [];

        foreach ($product['variants'] ?? [] as $variant) {
            $variantId = (int) ($variant['id'] ?? 0);
            if ($variantId <= 0) {
                continue;
            }

            $variants[] = [
                'id' => $variantId,
                'sku' => isset($variant['sku']) && $variant['sku'] !== '' ? (string) $variant['sku'] : null,
                'title' => (string) ($variant['title'] ?? 'Default'),
                'price_cents' => (int) ($variant['price_cents'] ?? $product['price_cents'] ?? 0),
                'currency' => $currency,
                'quantity' => $this->quantity($variant['quantity'] ?? $product['quantity'] ?? self::UNLIMITED),
            ];
        }

        if ($variants !== []) {
            return $variants;
        }

        return [[
            'id' => $productId * 10,
            'sku' => isset($product['sku']) && $product['sku'] !== '' ? (string) $product['sku'] : null,
            'title' => 'Default',
            'price_cents' => (int) ($product['price_cents'] ?? 0),
            'currency' => $currency,
            'quantity' => $this->quantity($product['quantity'] ?? self::UNLIMITED),
        ]];
    }

    /** @param array<int, int> $ids */
    private function deactivateMissing(array $ids): string
    {
        if ($ids === []) {
            return "UPDATE products SET is_active = 0;\n\n";
        }

        return 'UPDATE products SET is_active = 0 WHERE id NOT IN (' . implode(', ', $ids) . ");\n\n";
    }

    private function quantity(mixed $value): int
    {
        if ($value === null || $value === '' || $value === 'nolimit') {
            return self::UNLIMITED;
        }

        $quantity = (int) $value;

        return $quantity < 0 ? self::UNLIMITED : $quantity;
    }

    private function nullableQuote(mixed $value): string
    {
        if ($value === null || $value === '') {
            return 'NULL';
        }

        return $this->quote((string) $value);
    }

    private function quote(string $value): string
    {
        return "'" . str_replace("'", "''", $value) . "'";
    }
}
